s3:
    bucket: 
    region: 
    access_key: 
    secret_key: 
    interval: 3600
    

agents:
    -
        publishKey: 
        subscribeKey: 
        secretKey: 
        uuid: 
        channels:
            - ""